<?php
$Menu = array (
    //Menu[0] twofor
array('Title' => 'Two For Twenty',
    'ImageLoc' => './img/main/2for20.jpg',
    'Link' => './?category=twofor',
        array('Title' => 'Appetizers',
            'ImageLoc' => './img/twofor/mozzeralla_sticks.jpg',
            'Link' => './?category=Apps',
        array('Title' => 'Mozzarella Sticks',
            'ImageLoc' => './img/twofor/app/mozzarella_sticks.jpg'),
        array('Title' => 'Crunchy Onion Rings',
            'ImageLoc' => './img/twofor/app/onion_rings.jpg'),
        array('Title' => 'Two Side Salads(House or Caesar)',
            'ImageLoc' => './img/twofor/app/caesar_salad.jpg')),
        array('Title' => 'Entrees',
            'ImageLoc' => './img/twofor/allinburger.jpg',
            'Link' => './?category=Entree',
        array('Title' => 'Three-Cheese Chicken Penne', 'ImageLoc' => 'llama'),
        array('Title' => 'Chicken Tenders Basket', 'ImageLoc' => 'llama'),
        array('Title' => 'The American Standard', 'ImageLoc' => 'llama'))
),
    //Menu[1] better
array('Title' => 'Better For You',
    'ImageLoc' => './img/main/betterforyou.jpg',
    'Link' => './?category=better',
        array('Title' => 'The Smarter Choice',
        'ImageLoc' => './img/better4u/bourbon_chicken.jpg',
        array('Title' => 'Hot Shot Whiskey Chicken', 'ImageLoc' => 'llama'),
        array('Title' => 'Savory Cedar Salmon', 'ImageLoc' => 'llama'),
        array('Title' => 'Shrimp Wonton Stir-Fry', 'ImageLoc' => 'llama'))
),
    //Menu[2] Drinks
array('Title' => 'Beverages',
    'ImageLoc' => './img/main/beverages.jpg',
    'Link' => './?category=Drinks',
        array('Title' => 'Beers',
            'ImageLoc' => './img/beverages/Beers.jpg',
            'Link'=>'',
            array('Title' => 'Neighborhood Favorites',
                'ImageLoc' => 'llama',
                'Link' => ''
            ),
        array('Title' => 'Wines',
            'ImageLoc' => 'llama',
            'Link' => '')
),
        array('Title' => 'Refreshments',
            'ImageLoc' => './img/beverages/refreshments.jpg',
            'Link' => '',
            array( 'Title' => 'Tea',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'Lemonaid',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'Lime-aids',
                'ImageLoc' => 'llama',
                'Link' => ''))
),
    //Menu[3] Burgers
array('Title' => 'Burgers',
    'ImageLoc' => './img/main/burgers.jpg',
    'Link' => './?category=Burgers',
        array('Title' => 'Mushroom',
            'ImageLoc' => './img/burgers/burger_mushroomswiss.jpg',
            'Link' => ''),
        array('Title' => 'American',
            'ImageLoc' => './img/burgers/burger_american.jpg',
            'Link' => ''),
        array('Title' => 'TripleBacon',
            'ImageLoc' => './img/burgers/burger_triplebacon.jpg',
            'Link' => '')),
    //Menu[4] Desserts
array('Title' => 'Desserts',
'ImageLoc' => './img/main/desserts.jpg',
'Link' => './?category=Desserts',
        array('Title' => 'TripleChoc',
        'ImageLoc' => './img/desserts/triple_choc.jpg',
            'Link' => ''),
        array('Title' => 'MapleBlonde',
            'ImageLoc' => './img/desserts/maple_blondie.jpg',
            'Link' => ''),
        array('Title' => 'AppleCheeseCake',
            'ImageLoc' => './img/desserts/apple_cheesecake.jpg',
            'Link' => '')
),
    //Menu[5] MainEntree
 array('Title' => 'MainEntrees',
     'ImageLoc' => './img/main/entree_main_dishes.jpg',
     'Link' => './?category=MainEntree',
        array('Title' => 'Steak',
            'ImageLoc' => './img/mainEntrees/steak.jpg',
            'Link' => '',
                array('Title' => 'GrilledOnionSirloin',
                    'ImageLoc' => '',
                    'Link' => ''),
                array('Title' => 'Sirloin',
                    'ImageLoc' => 'llama',
                    'Link' => ''),
                array('Title' => 'PepperSirloin',
                    'ImageLoc' => 'llama',
                    'Link' => '')),
        array('Title' => 'Ribs',
            'ImageLoc' => './img/mainEntrees/ribs.jpg',
            'Link' => '',
                array('Title' => 'Riblets',
                    'ImageLoc' => 'llama',
                    'Link' => ''),
                array('Title' => 'BabyBack',
                    'ImageLoc' => 'llama',
                    'Link' => '')),
        array('Title' => 'Chicken',
            'ImageLoc' => './img/mainEntrees/chicken.jpg',
            'Link' => '',
                array('Title' => 'BrewHouse',
                    'ImageLoc' => 'llama',
                    'Link' => ''),
                array('Title' => 'BurbonChicken',
                    'ImageLoc' => 'llama',
                    'Link' => ''),
                array('Title' => 'ChickenTend',
                    'ImageLoc' => 'llama',
                    'Link' => '')),
),
    //Menu[6] Lunch
array('Title' => 'Lunch Combos',
   'ImageLoc' => './img/main/lunch_combos.jpg',
   'Link' => './?category=Lunch',
        array('Title' => 'Tomato Basil Soup +  French Onion Soup',
           'ImageLoc' => './img/lunchCombos/oriental_salad.jpg',
           'Link' => ''),
        array('Title' => 'House Salad(contains bacon) + Clubhouse Grille',
           'ImageLoc' => './img/lunchCombos/shrimp.jpg',
           'Link' => ''),
         array('Title' => 'Chicken Fajita Rollup + Shrimp Scampi Linguine',
           'ImageLoc' => './img/lunchCombos/meatballs.jpg',
           'Link' => '')),
    //Menu[7] Salads
array('Title' => 'Salads',
    'ImageLoc' => './img/main/salads.jpg',
    'Link' => './?category=Salads',
        array('Title' => 'ThaiShrimp',
            'ImageLoc' => './img/salads/ThaiShrimp.jpg',
            'Link' => ''),
        array('Title' => 'FiestaChicken',
            'ImageLoc' => './img/salads/FiestaChicken.jpg',
            'Link' => ''),
        array('Title' => 'ChickenCeasar',
            'ImageLoc' => './img/salads/ChickenCeasar.jpg',
            'Link' => '')
),
    //Menu[8] Pub
array('Title' => 'PubDiet',
    'ImageLoc' => './img/main/pubdiet.jpg',
    'Link' => './?category=Pub',
        array('Title' => 'ShrimpWonton',
            'ImageLoc' => './img/pubdiet/ShrimpWonton.jpg',
            'Link' => ''),
        array('Title' => 'SirloinStout',
            'ImageLoc' => './img/pubdiet/SirloinStout.jpg',
            'Link' => ''),
        array('Title' => 'CedarChicken',
            'ImageLoc' => './img/pubdiet/CedarChicken.jpg',
            'Link' => '')
),
    //Menu[9] Handhelds
array('Title' => 'Handhelds',
    'ImageLoc' => './img/main/handhelds.jpg',
    'Link' => './?category=Handhelds',
        array('Title' => 'New Triple Hog Dare Ya',
            'ImageLoc' => './img/Handhelds/triple_hog_dare_ya.jpg',
            'Link' => ''),
        array('Title' => 'New Kickin Turkey Stacker',
            'ImageLoc' => './img/Handhelds/turkey_stacker.jpg',
            'Link' => ''),
        array('Title' => 'American BLT',
            'ImageLoc' => './img/Handhelds/blt.jpg',
            'Link' => '')),
    //Menu[10] Kids
array('Title' => 'Kids',
    'ImageLoc' => './img/main/kids.jpg',
    'Link' => './?category=kids',
        array('Title' => 'Kid1',
            'ImageLoc' => './img/kids/kid1.jpg',
            'Link' => ''),
        array('Title' => 'Kid2',
            'ImageLoc' => './img/kids/kid2.jpg',
            'Link' => ''),
        array('Title' => 'Kid3',
            'ImageLoc' => './img/kids/kid3.jpg',
            'Link' => '')),
    //Menu[11] Bar
array('Title' => 'Bar Snacks',
    'ImageLoc' => './img/main/barSnacks.jpg',
    'Link' => './?category=Bar',
        array('Title' => 'Shrimp',
            'ImageLoc' => './img/ikea/lemon_chicken.jpg',
            'Link' => ''),
        array('Title' => 'Meatballs',
            'ImageLoc' => './img/ikea/lemon_chicken.jpg',
            'Link' => ''),
        array('Title' => 'Smores',
            'ImageLoc' => './img/ikea/lemon_chicken.jpg'))
);
?>
<!--<p>-->
<!--    --><?php //var_dump($menu) ?>
<!--</p>-->
