<?php
$Menu = array (
    array('Title' => 'Two For Twenty',
        'ImageLoc' => './img/main/2420.jpg',
        'Link' => './?cat=twofor',
        array('Title' => 'Appetizers',
            'ImageLoc' => './img/main/apps.jpg',
            'Link' => './?cat=twofor1',
            array('Title' => 'Mozzarella Sticks',
                'ImageLoc' => './img/twofor/mozzarella_sticks.jpg'),
            array('Title' => 'Crunchy Onion Rings',
                'ImageLoc' => './img/twofor/onion_rings.jpg'),
            array('Title' => 'Two Side Salads(House or Caesar)',
                'ImageLoc' => './img/twofor/caesar_salad.jpg')),
        array('Title' => 'Entrees',
            'ImageLoc' => './img/twofor/chicken_penne.jpg',
            'Link' => './?cat=twofor2',
            array('Title' => 'Three-Cheese Chicken Penne', 'ImageLoc' => './img/twofor/chicken_penne.jpg'),
            array('Title' => 'Chicken Tenders Basket', 'ImageLoc' => './img/twofor/chicken_tend.jpg'),
            array('Title' => 'The American Standard', 'ImageLoc' => './img/twofor/allinburger.jpg'))
    ),
    array('Title' => 'Better For You',
        'ImageLoc' => './img/main/better4u.jpg',
        'Link' => './?cat=better',
        array('Title' => 'Hot Shot Whiskey Chicken', 'ImageLoc' => './img/better4u/bourbon_chicken.jpg'),
        array('Title' => 'Savory Cedar Salmon', 'ImageLoc' => './img/better4u/salmon.jpg'),
        array('Title' => 'Shrimp Wonton Stir-Fry', 'ImageLoc' => './img/better4u/shrimpWonton.jpg')
    ),
    array('Title' => 'Lunch Combos',
        'ImageLoc' => './img/main/LunchCombos.jpg',
        'Link' => './?cat=lunch',
        array('Title' => 'Tomato Basil Soup +  French Onion Soup',
            'ImageLoc' => './img/lunchCombos/meatballs.jpg'),
        array('Title' => 'House Salad(contains bacon) + Clubhouse Grille',
            'ImageLoc' => './img/lunchCombos/oriental_salad.jpg'),
        array('Title' => 'Chicken Fajita Rollup + Shrimp Scampi Linguine',
            'ImageLoc' => './img/lunchCombos/shrimp.jpg')
    ),
    array('Title' => 'Main Entrees',
        'ImageLoc' => './img/main/entrees.jpg',
        'Link' => './?cat=main_1',
        array('Title' => 'Steaks',
            'ImageLoc' => './img/mainEntrees/steak.jpg',
            'Link' => './?cat=main1',
            array('Title' => '7oz Grilled Onion Sirloin with Stout Gravy',
                'ImageLoc' => './img/mainEntrees/grilled_onion_sirloin.jpg'),
            array('Title' => '9oz House Sirloin',
                'ImageLoc' => './img/mainEntrees/sirloin.jpg'),
            array('Title' => 'Pepper-Crusted Sirloin & Whole Grains',
                'ImageLoc' => './img/mainEntrees/pepper_sirloin.jpg')),
        array('Title' => 'Ribs',
            'ImageLoc' => './img/mainEntrees/riblets.jpg',
            'Link' => './?cat=main2',
            array('Title' => 'Applebee\'s Riblets',
                'ImageLoc' => './img/mainEntrees/riblets.jpg'),
            array('Title' => 'Double-Glazed Baby Back Ribs',
                'ImageLoc' => './img/mainEntrees/ribs.jpg')),
        array('Title' => 'Chicken',
            'ImageLoc' => './img/mainEntrees/bourbon_chicken.jpg',
            'Link' => './?cat=main3',
            array('Title' => 'Crispy Chicken Brewhouse',
                'ImageLoc' => './img/mainEntrees/brewhouse_chicken.jpg'),
            array('Title' => 'Bourbon Street Chicken & Shrimp', 'ImageLoc' => './img/mainEntrees/bourbon_chicken.jpg'),
            array('Title' => 'Chicken Tenders Platter',
                'ImageLoc' => './img/mainEntrees/chicken_tenders.jpg')),
        array('Title' => 'Pasta, Seafood & More',
            'ImageLoc' => './img/better4u/salmon.jpg',
            'Link' => './?cat=main4',
            array('Title' => 'Shrimp Wonton Stir-Fry',
                'ImageLoc' => './img/better4u/salmon.jpg'),
            array('Title' => 'Savory Cedar Salmon',
                'ImageLoc' => './img/better4u/salmon.jpg'),
            array('Title' => 'Three-Cheese Chicken Penne',
                'ImageLoc' => './img/better4u/salmon.jpg')),
        array('Title' => 'Sides',
            'ImageLoc' => './img/better4u/salmon.jpg',
            'Link' => './?cat=main5',
            array('Title' => 'Green Goddess Wedge',
                'ImageLoc' => './img/better4u/salmon.jpg'),
            array('Title' => 'Tomato Basil Soup',
                'ImageLoc' => './img/better4u/salmon.jpg'),
            array('Title' => 'French Onion Soup',
                'ImageLoc' => './img/better4u/salmon.jpg')),
    ),
    array('Title' => 'New Apps & Bar Snacks',
        'ImageLoc' => './img/main/apps.jpg',
        'Link' => './?cat=snacks',
        array('Title' => 'Sriracha Shrimp',
            'ImageLoc' => './img/snacks/srirachaShrimp.jpg'),
        array('Title' => 'Kobe Meatballs',
            'ImageLoc' => './img/snacks/kobeMeatballs.jpg'),
        array('Title' => 'Churro Smores',
            'ImageLoc' => './img/snacks/churroSmores.jpg')
    ),
    array('Title' => 'Handcrafted Burgers',
        'ImageLoc' => './img/main/handcraftedHamburger.jpg',
        'Link' => './?cat=burgers',
        array('Title' => 'All-In Burgers',
            'ImageLoc' => './img/burgers/burger_mushroomswiss.jpg',
            'Link' => './?cat=burgers1',
            array('Title' => 'Mushroom Swiss',
                'ImageLoc' => './img/burgers/burger_mushroomswiss.jpg'),
            array('Title' => 'The American Standard',
                'ImageLoc' => './img/burgers/burger_american.jpg'),
            array('Title' => 'Triple Bacon Burger',
                'ImageLoc' => './img/burgers/burger_triplebacon.jpg')),
        array('Title' => 'Neighborhood Burgers',
            'ImageLoc' => './img/burgers/burger_triplebacon.jpg',
            'Link' => './?cat=burgers2',
            array('Title' => 'Cowboy Burger',
                'ImageLoc' => './img/burgers/burger_triplebacon.jpg'),
            array('Title' => 'Quesadilla Burger',
                'ImageLoc' => './img/burgers/burger_american.jpg'),
            array('Title' => 'The Classic',
                'ImageLoc' => './img/burgers/burger_mushroomswiss.jpg'))
    ),
    array('Title' => 'New Handhelds',
        'ImageLoc' => './img/main/handHeld.jpg',
        'Link' => './?cat=handhelds',
        array('Title' => 'Triple Hog Dare Ya',
            'ImageLoc' => './img/Handhelds/triple_hog_dare_ya.jpg'),
        array('Title' => 'Kickin Turkey Stacker',
            'ImageLoc' => './img/Handhelds/turkey_stacker.jpg'),
        array('Title' => 'American BLT',
            'ImageLoc' => './img/Handhelds/blt.jpg')
    ),
    array('Title' => 'Fresh Salads',
        'ImageLoc' => './img/main/salads.jpg',
        'Link' => './?cat=salads',
        array('Title' => 'Thai Shrimp Salad',
            'ImageLoc' => './img/salads/ThaiShrimp.jpg'),
        array('Title' => 'Fiesta Chicken Chopped Salad',
            'ImageLoc' => './img/salads/FiestaChicken.jpg'),
        array('Title' => 'Grilled Chicken Caesar Salad',
            'ImageLoc' => './img/salads/ChickenCeasar.jpg')
    ),
    array('Title' => 'Pub Diet',
        'ImageLoc' => './img/main/pubDiet.jpg',
        'Link' => './?cat=pub',
        array('Title' => 'Shrimp Wonton Stir-Fry',
            'ImageLoc' => './img/pubdiet/ShrimpWonton.jpg'),
        array('Title' => '7oz Grilled Onion Sirloin with Stout Gravy',
            'ImageLoc' => './img/pubdiet/SirloinStout.jpg'),
        array('Title' => 'Cedar Grilled Lemon Chicken',
            'ImageLoc' => './img/pubdiet/CedarChicken.jpg')
    ),
    array('Title' => 'Kids',
        'ImageLoc' => './img/main/kids.jpg',
        'Link' => './?cat=kids',
        array('Title' => 'Smores',
            'ImageLoc' => './img/ikea/smores.jpg'),
        array('Title' => 'Smore Smores',
            'ImageLoc' => './img/ikea/smores.jpg'),
        array('Title' => 'Smore Smore Smores',
            'ImageLoc' => './img/ikea/smores.jpg')
    ),
    array('Title' => 'Desserts',
        'ImageLoc' => './img/main/desserts.jpg',
        'Link' => './?cat=desserts',
        array('Title' => 'Triple Chocolate Meltdown',
            'ImageLoc' => './img/desserts/triple_choc.jpg'),
        array('Title' => 'Butter Pecan Blondie',
            'ImageLoc' => './img/desserts/maple_blondie.jpg'),
        array('Title' => 'Apple Chimi-Cheesecake',
            'ImageLoc' => './img/desserts/apple_cheesecake.jpg')
    ),
    array('Title' => 'Beverages',
        'ImageLoc' => './img/main/beverages.jpg',
        'Link' => './?cat=drinks',
        array('Title' => 'Beers',
            'ImageLoc' => './img/beverages/Beers.jpg',
            'Link'=>'./?cat=drinks1',
            array('Title' => 'Neighborhood Favorites',
                'ImageLoc' => './img/beverages/beer.jpg'
            )),
        array('Title' => 'Wines',
            'ImageLoc' => './img/beverages/wines.jpg',
            'Link' => './?cat=drinks2',
            array('Title' => 'Neighborhood Favorites',
                'ImageLoc' => './img/beverages/wine_toast.jpg'
            )),
        array('Title' => 'Refreshments',
            'ImageLoc' => './img/beverages/refreshments.jpg',
            'Link' => './?cat=drinks3',
            array( 'Title' => 'Tea',
                'ImageLoc' => './img/beverages/tea.jpg'),
            array('Title' => 'Lemonade',
                'ImageLoc' => './img/beverages/lemonades.jpg'),
            array('Title' => 'Limeade',
                'ImageLoc' => './img/beverages/limeades.jpg'))
    ),
);
?>